import "~/styles/globals.css";
import { getServerAuthSession } from "~/server/auth";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import Provider from "./context/Provider";
import { TRPCReactProvider } from "~/trpc/react";
import NavBar from "./_components/NavBar";
import StatBar from "./_components/StatBar";
import bg from "./_components/img/body-background-img-rock.png"
import tg from "./_components/img/tgc.png"
import SideBar from "./_components/SideBar";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html lang="en"style={{
      backgroundImage: `url(${bg.src})`,
      width: '100%',
      height: '100%',
    }}>
      <body className={`font-sans ${inter.variable}`}>
        <Provider session = {session}>
        <TRPCReactProvider cookies={cookies().toString()}>
        <header className="header" style={{
          backgroundImage: `url(${tg.src})`,
          backgroundSize: 'cover',
          backgroundRepeat: 'no-repeat',
          backgroundPosition: 'center',
          width: '100%',
          height: '100%',
          position:'relative',
          minHeight: '40vh',
        }}>
          <StatBar />
          <SideBar />
          <NavBar />
        </header>
          {children}
        </TRPCReactProvider>
        </Provider>
      </body>
    </html>
  );
}
